# Generated by Django 4.1 on 2022-08-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('accountNumber', models.CharField(max_length=20)),
                ('account', models.CharField(choices=[('S', 'Saving Account'), ('C', 'Checkin Account'), ('FD', 'Fixed Deposite')], max_length=2)),
                ('password', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=None)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
